# Generated by Django 3.2.6 on 2021-08-11 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Familiares',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_padre', models.CharField(max_length=50)),
                ('No_identificacion_padre', models.IntegerField()),
                ('Telefono_padre', models.IntegerField()),
                ('Edad_padre', models.IntegerField()),
                ('Ocupacion_padre', models.CharField(max_length=20)),
                ('Estudios_padre', models.CharField(max_length=20)),
                ('direccion_padre', models.CharField(max_length=40)),
                ('nombre_madre', models.CharField(max_length=50)),
                ('No_identificacion_madre', models.IntegerField()),
                ('Telefono_madre', models.IntegerField()),
                ('Edad_madre', models.IntegerField()),
                ('Ocupacion_madre', models.CharField(max_length=20)),
                ('Estudios_madre', models.CharField(max_length=20)),
                ('direccion_madre', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Ingresados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('No_identificacion', models.IntegerField()),
                ('Telefono', models.IntegerField()),
                ('Edad', models.IntegerField()),
                ('Tipo_sangre', models.CharField(max_length=4)),
                ('EPS', models.CharField(max_length=20)),
                ('institucion', models.CharField(max_length=40)),
                ('materia', models.CharField(max_length=20)),
                ('direccion', models.CharField(max_length=40)),
            ],
        ),
    ]
